version: '3.8'

services:
  web:
    image: flask-mongodb-app:latest
    build: .
    ports:
      - "5000:5000"
    deploy:
      replicas: 2  # Scale to 2 replicas
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager] 

volumes:
  mongodb_data: