version: '3.8'

services:
  web:
    image: flask-mongodb-app:latest
    build: .
    ports:
      - "5000:5000"
    deploy:
      replicas: 2  # Scale to 2 replicas
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      mongodb:
        condition: service_healthy  # Wait until MongoDB is healthy
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/mydatabase  # Pass MongoDB URL
    networks:
      - app_network 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:  # Health check for MongoDB
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app_network  

volumes:
  mongodb_data:

networks:
  app_network:  # Define a custom network
